### PR TITLE
Initializing the Terraform setup.

### PR DESCRIPTION
**Pull request by ringods**
@josephholsten I initiated a PR of your initial work to make sure it ends up on `master` before I continue adding new setup. Can you get this to `master`?

### CODE REVIEW

**Comment by ringods** [comment]
Ping @josephholsten ;-)

**Comment by ringods** [comment]
Ping @josephholsten

**Review by rowleyaj — APPROVED** [review]

**Comment by ringods** [comment]
Where should we store the Terraform state? The `sous-chefs` project uses this:

https://github.com/sous-chefs/terraform-github-org/blob/7058c2e1dadf331b7ff45bbd35820e0e1b60cca3/main.tf#L11-L15

But Atlas has been replaced with Terraform Enterprise and is no longer freely accessible if I'm not mistaken.

One requirement is that org owners/admins should have read access on their workstation so they are able to run `terraform plan` and see the output before submitting/testing PRs.
Here is the list of currently supported backends:
https://www.terraform.io/docs/backends/types/index.html

**Comment by josephholsten** [comment]
I’m so sorry for neglecting this! In sous-chefs, we have a terraform enterprise account thanks to hashicorp’s generosity. I’ll go ask if we can have similar for terra-farm.

**Comment by ringods** [comment]
@josephholsten please do. I guess that also means that I don't have to setup Travis CI for plan/apply, right?

**Comment by ringods** [comment]
@rowleyaj @josephholsten please review again before merging. The membership resources have been imported into the state already, so once this is on `master` the TF run by Terraform Enterprise should be a no-op.

**Review by rowleyaj — APPROVED** [review]

**Pull request merged**
